### ISSUE TITLE
having issue with installing node packes

### ISSUE THREAD

**Issue by Bouncyknighter** [jamesbachini/JANG-Just-Another-NFT-Generator#2]
npm node install 
idealTree: timing idealTree Completed in 10727ms

**Comment by jamesbachini** [comment]
Hey I think it's a cache issue with npm. Check out this thread:
https://stackoverflow.com/questions/69161318/npm-stuck-on-idealtree-timing-idealtree

1. Kill the npm install process with ctrl+c.

2. Delete node_modules. If there are files that you cannot delete because they are currently in use, that may mean that the npm install process was not successfully stopped. Try opening Task Manager and ending all nodejs and terminal processes. If this fails, restart your pc and then delete node_modules

3. Clean cache and reinstall node_modules with npm cache clean --force && npm i

**Comment by Bouncyknighter** [comment]
Okay, so I think there was a problem with my Node JS, I have windows 11 and the version 16.16 or 18.7 doesnt let me install the package image compression npm or the canvas. I have uninstalled the nodejs on my pc but now i cant reinstall it back. 
I think it will work on windows 10 without any problem. Issue was with the OS and the Node JS compatibility.
